services:
  - type: web
    name: t1mechat
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
